version: '3'
services:
  channeld:
    profiles:
      - donotstart
    build:
      dockerfile: Dockerfile
    image: channeld/channeld
    depends_on:
      - prometheus
    ports:
      - "12108:12108"
    expose:
      - "11288"
    entrypoint: ["./app", "-cfsm", "../config/client_authoratative_fsm.json"]
  tanks:
    profiles:
      - donotstart
    image: channeld/tanks
    depends_on:
      - channeld
    environment:
      - CHANNELD_IP=channeld
  chat:
    build:
      context: .
      dockerfile: examples/chat-rooms/Dockerfile
    image: channeld/chat
    depends_on:
      - prometheus
    deploy:
      resources:
        limits:
          cpus: "3.5"
        reservations:
          cpus: "2"
    ports:
      - "8080:8080"
      - "12108:12108"
    expose:
      - "8080"
      - "12108"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    expose:
      - "3000"
  prometheus:
    image: prom/prometheus
    entrypoint: /bin/sh -c
    command: |
      'sh -s <<EOF
        cat > ./prometheus.yml <<EON
      global:
        scrape_interval:     1s
        evaluation_interval: 1s
      scrape_configs:
        - job_name: channeld
          static_configs:
          - targets: ['chat:8080']
      EON
      prometheus --config.file=./prometheus.yml
      EOF'
    ports:
      - '9090:9090'